---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  client_rb:
    ssl_verify_mode: :verify_none # Chef outputs an ugly SSL warning otherwise

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[pgbouncer::example]
